---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: blog-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "wu823892"
            - name: MYSQL_USER
              value: "carrotwu"
            - name: MYSQL_PASSWORD
              value: "wu823892"
            - name: TZ
              value: "Asia/Shanghai"
          args: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_general_ci","--explicit_defaults_for_timestamp=true","--lower_case_table_names=1","--max_allowed_packet=128M","--innodb_buffer_pool_size=64M","--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: blog-project
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    app: mysql

