global:
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: '542425997@qq.com'
  smtp_auth_username: '542425997@qq.com'
  # qq邮箱获取的授权码
  smtp_auth_password: 'geyzjhcdudynbdef'
  smtp_require_tls: false

#templates:
#  - '/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: ''542425997@qq.com''
        send_resolved: true
